# coding: utf-8

"""
    ChannelEngine API V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2.1.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.cancellation_api import CancellationApi


class TestCancellationApi(unittest.TestCase):
    """ CancellationApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.cancellation_api.CancellationApi()

    def tearDown(self):
        pass

    def test_cancellation_create(self):
        """
        Test case for cancellation_create

        Merchant: Create Cancellation
        """
        pass

    def test_cancellation_index(self):
        """
        Test case for cancellation_index

        Channel: Get Cancellations
        """
        pass


if __name__ == '__main__':
    unittest.main()
