# coding: utf-8

"""
    ChannelEngine API V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2.1.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.channel_return_line_response import ChannelReturnLineResponse


class TestChannelReturnLineResponse(unittest.TestCase):
    """ ChannelReturnLineResponse unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChannelReturnLineResponse(self):
        """
        Test ChannelReturnLineResponse
        """
        model = swagger_client.models.channel_return_line_response.ChannelReturnLineResponse()


if __name__ == '__main__':
    unittest.main()
