# coding: utf-8

"""
    ChannelEngine API V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2.1.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.offer_api import OfferApi


class TestOfferApi(unittest.TestCase):
    """ OfferApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.offer_api.OfferApi()

    def tearDown(self):
        pass

    def test_offer_stock_price_update(self):
        """
        Test case for offer_stock_price_update

        Update stock or price.
        """
        pass


if __name__ == '__main__':
    unittest.main()
