# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from channelengine_merchant_api_client.models.merchant_return_line_update_request import MerchantReturnLineUpdateRequest  # noqa: F401,E501


class MerchantReturnUpdateRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'return_id': 'int',
        'lines': 'list[MerchantReturnLineUpdateRequest]'
    }

    attribute_map = {
        'return_id': 'ReturnId',
        'lines': 'Lines'
    }

    def __init__(self, return_id=None, lines=None):  # noqa: E501
        """MerchantReturnUpdateRequest - a model defined in Swagger"""  # noqa: E501

        self._return_id = None
        self._lines = None
        self.discriminator = None

        self.return_id = return_id
        self.lines = lines

    @property
    def return_id(self):
        """Gets the return_id of this MerchantReturnUpdateRequest.  # noqa: E501

        The ChannelEngine return ID of the return you would like to update  # noqa: E501

        :return: The return_id of this MerchantReturnUpdateRequest.  # noqa: E501
        :rtype: int
        """
        return self._return_id

    @return_id.setter
    def return_id(self, return_id):
        """Sets the return_id of this MerchantReturnUpdateRequest.

        The ChannelEngine return ID of the return you would like to update  # noqa: E501

        :param return_id: The return_id of this MerchantReturnUpdateRequest.  # noqa: E501
        :type: int
        """
        if return_id is None:
            raise ValueError("Invalid value for `return_id`, must not be `None`")  # noqa: E501

        self._return_id = return_id

    @property
    def lines(self):
        """Gets the lines of this MerchantReturnUpdateRequest.  # noqa: E501


        :return: The lines of this MerchantReturnUpdateRequest.  # noqa: E501
        :rtype: list[MerchantReturnLineUpdateRequest]
        """
        return self._lines

    @lines.setter
    def lines(self, lines):
        """Sets the lines of this MerchantReturnUpdateRequest.


        :param lines: The lines of this MerchantReturnUpdateRequest.  # noqa: E501
        :type: list[MerchantReturnLineUpdateRequest]
        """
        if lines is None:
            raise ValueError("Invalid value for `lines`, must not be `None`")  # noqa: E501

        self._lines = lines

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MerchantReturnUpdateRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
