# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants  # noqa: E501

    The version of the OpenAPI document: 2.9.3
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from channelengine_merchant_api_client.configuration import Configuration


class MerchantProductBundlePartResponse(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'merchant_product_no': 'str',
        'ean': 'str',
        'name': 'str',
        'quantity': 'int',
        'price': 'float'
    }

    attribute_map = {
        'merchant_product_no': 'MerchantProductNo',
        'ean': 'Ean',
        'name': 'Name',
        'quantity': 'Quantity',
        'price': 'Price'
    }

    def __init__(self, merchant_product_no=None, ean=None, name=None, quantity=None, price=None, local_vars_configuration=None):  # noqa: E501
        """MerchantProductBundlePartResponse - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._merchant_product_no = None
        self._ean = None
        self._name = None
        self._quantity = None
        self._price = None
        self.discriminator = None

        self.merchant_product_no = merchant_product_no
        self.ean = ean
        self.name = name
        if quantity is not None:
            self.quantity = quantity
        if price is not None:
            self.price = price

    @property
    def merchant_product_no(self):
        """Gets the merchant_product_no of this MerchantProductBundlePartResponse.  # noqa: E501


        :return: The merchant_product_no of this MerchantProductBundlePartResponse.  # noqa: E501
        :rtype: str
        """
        return self._merchant_product_no

    @merchant_product_no.setter
    def merchant_product_no(self, merchant_product_no):
        """Sets the merchant_product_no of this MerchantProductBundlePartResponse.


        :param merchant_product_no: The merchant_product_no of this MerchantProductBundlePartResponse.  # noqa: E501
        :type merchant_product_no: str
        """

        self._merchant_product_no = merchant_product_no

    @property
    def ean(self):
        """Gets the ean of this MerchantProductBundlePartResponse.  # noqa: E501


        :return: The ean of this MerchantProductBundlePartResponse.  # noqa: E501
        :rtype: str
        """
        return self._ean

    @ean.setter
    def ean(self, ean):
        """Sets the ean of this MerchantProductBundlePartResponse.


        :param ean: The ean of this MerchantProductBundlePartResponse.  # noqa: E501
        :type ean: str
        """

        self._ean = ean

    @property
    def name(self):
        """Gets the name of this MerchantProductBundlePartResponse.  # noqa: E501


        :return: The name of this MerchantProductBundlePartResponse.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this MerchantProductBundlePartResponse.


        :param name: The name of this MerchantProductBundlePartResponse.  # noqa: E501
        :type name: str
        """

        self._name = name

    @property
    def quantity(self):
        """Gets the quantity of this MerchantProductBundlePartResponse.  # noqa: E501


        :return: The quantity of this MerchantProductBundlePartResponse.  # noqa: E501
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity):
        """Sets the quantity of this MerchantProductBundlePartResponse.


        :param quantity: The quantity of this MerchantProductBundlePartResponse.  # noqa: E501
        :type quantity: int
        """

        self._quantity = quantity

    @property
    def price(self):
        """Gets the price of this MerchantProductBundlePartResponse.  # noqa: E501


        :return: The price of this MerchantProductBundlePartResponse.  # noqa: E501
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this MerchantProductBundlePartResponse.


        :param price: The price of this MerchantProductBundlePartResponse.  # noqa: E501
        :type price: float
        """

        self._price = price

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MerchantProductBundlePartResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, MerchantProductBundlePartResponse):
            return True

        return self.to_dict() != other.to_dict()
